const estudantes = [
    {nome: 'Ana', idade: 20},
    {nome: 'João', idade: 21},
    {nome: 'Maria', idade: 19},
    {nome: 'Pedro', idade: 22},
    {nome: 'Fernanda', idade: 18},
    {nome: 'Carlos', idade: 25},
    {nome: 'Lucas', idade: 21},
    {nome: 'Beatriz', idade: 24},
    {nome: 'Roberto', idade: 30},
    {nome: 'Marta', idade: 27},
    {nome: 'Diego', idade: 22},
    {nome: 'Camila', idade: 19},
    {nome: 'Renata', idade: 28},
    {nome: 'Henrique', idade: 21},
    {nome: 'Victor', idade: 23},
    {nome: 'Sofia', idade: 20},
    {nome: 'Raquel', idade: 29},
    {nome: 'Rafael', idade: 26},
    {nome: 'Daniela', idade: 18},
    {nome: 'Luis', idade: 31},
    {nome: 'Isabella', idade: 20},
    {nome: 'Amanda', idade: 19},
    {nome: 'Leonardo', idade: 24},
    {nome: 'Gabriela', idade: 22},
    {nome: 'Marcelo', idade: 27},
    {nome: 'Ricardo', idade: 25},
    {nome: 'Felipe', idade: 19},
    {nome: 'Letícia', idade: 28},
    {nome: 'Natália', idade: 26},
    {nome: 'Bruno', idade: 23},
    {nome: 'Thiago', idade: 21},
    {nome: 'André', idade: 30},
    {nome: 'Juliana', idade: 18},
    {nome: 'Gustavo', idade: 19},
    {nome: 'Fábio', idade: 21},
    {nome: 'Eduardo', idade: 29},
    {nome: 'Cláudia', idade: 26},
    {nome: 'Bianca', idade: 19},
    {nome: 'Cristiane', idade: 28},
    {nome: 'Márcio', idade: 31},
    {nome: 'Júlia', idade: 20},
    {nome: 'Caio', idade: 21},
    {nome: 'Carolina', idade: 19},
    {nome: 'Patrícia', idade: 23},
    {nome: 'Alex', idade: 25},
    {nome: 'Vanessa', idade: 24},
    {nome: 'Mônica', idade: 27},
    {nome: 'Luana', idade: 22},
    {nome: 'Vitor', idade: 19},
    {nome: 'Isadora', idade: 28}
];

const age20 = estudantes.find(age => age.idade === 20);

console.log(age20);
